# Generated by Django 6.0.6 on 2026-06-23 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, verbose_name='Código de lote')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
