# Generated by Django 6.0.6 on 2026-06-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_cost_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Código de barras (EAN-13)'),
        ),
    ]
