# Generated by Django 6.0.6 on 2026-07-07 15:05

from django.db import migrations, models


def normalizar_codigos_lote(apps, schema_editor):
    ProductBatch = apps.get_model('products', 'ProductBatch')
    from collections import defaultdict
    contadores = defaultdict(lambda: 1)
    for batch in ProductBatch.objects.all().order_by('product_id', 'id'):
        n = contadores[batch.product_id]
        batch.batch_code = f'LOTE-{batch.product_id}-{n:04d}'
        batch.save(update_fields=['batch_code'])
        contadores[batch.product_id] = n + 1


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_codigo'),
    ]

    operations = [
        migrations.RunPython(normalizar_codigos_lote, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productbatch',
            name='batch_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de lote'),
        ),
    ]
