# Generated by Django 6.0.6 on 2026-07-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productbatch_batch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True, verbose_name='Código de barras (EAN-13)'),
        ),
    ]
