# Generated by Django 6.0.6 on 2026-07-13 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=13)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('consumed', 'Consumido')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_queue_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Escaneo en cola',
                'verbose_name_plural': 'Escaneos en cola',
                'ordering': ['-created_at'],
            },
        ),
    ]
