# Generated by Django on 2026-07-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_scanqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Bloqueado para edición después de venta'),
        ),
    ]
