# Generated by Django 6.0.6 on 2026-07-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transfer_bank',
            field=models.CharField(blank=True, choices=[('bcp', 'BCP'), ('interbank', 'Interbank')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='yape_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='yape_type',
            field=models.CharField(blank=True, choices=[('qr', 'QR'), ('code', 'Código de aprobación')], default='', max_length=10),
        ),
    ]
