# Generated by Django 6.0.6 on 2026-07-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_transfer_bank_order_yape_code_order_yape_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='generated_yape_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
