# Generated by Django 6.0.6 on 2026-07-05 04:45

from django.db import migrations


def migrate_order_statuses(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    # Map old statuses to new ones
    status_map = {
        'confirmed': 'pending',
        'preparing': 'pending',
        'delivered': 'completed',
        # 'pending', 'ready' and 'cancelled' stay as-is
    }
    for old, new in status_map.items():
        Order.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_completed_at_order_completed_by_order_ready_at_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_order_statuses),
    ]
