# Generated by Django 6.0.6 on 2026-07-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_migrate_order_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
