# Generated by Django 6.0.6 on 2026-07-20 00:14

from django.db import migrations, models


def backfill_cartitem_prices(apps, schema_editor):
    CartItem = apps.get_model("orders", "CartItem")
    for item in CartItem.objects.filter(price=0).select_related("product"):
        item.price = item.product.price
        item.save(update_fields=["price"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_backfill_sales_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_cartitem_prices, migrations.RunPython.noop),
    ]
