# Generated by Django 6.0.6 on 2026-07-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('yape', 'Yape'), ('plin', 'Plin'), ('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('transferencia_bcp', 'Transferencia BCP'), ('transferencia_interbank', 'Transferencia Interbank')], default='', max_length=30),
        ),
    ]
