# Generated by Django 6.0.6 on 2026-07-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='colorblind_mode',
            field=models.BooleanField(default=False, verbose_name='Modo daltonismo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hearing_impaired_mode',
            field=models.BooleanField(default=False, verbose_name='Modo discapacidad auditiva'),
        ),
    ]
