# Generated by Django 6.0.6 on 2026-06-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante'),
        ),
    ]
